env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

rules:
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  react/function-component-definition: 0
  react/no-unknown-property: 0
  jsx-a11y/label-has-associated-control: 0
  react/jsx-no-constructed-context-values: 0
  jsx-a11y/no-autofocus: 0